# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
