# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
