# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
