# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_offer_tnc'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerreview',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offerreview',
            name='sentiment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
