# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20160507_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerreview',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerreview',
            name='sentiment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
