# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
